spring.application.name=auth-service
server.port=8081

spring.config.import=optional:configserver:http://localhost:8888

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/music_library_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Don't crash if Eureka is slow to start
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.instance.lease-renewal-interval-in-seconds=5
spring.cloud.discovery.enabled=true

# CORS
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*