spring.application.name=api-gateway
server.port=8080

spring.config.import=optional:configserver:http://localhost:8888

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=false

# Fix duplicate CORS headers
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

# Route to auth-service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Route to user-service
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

# Route to song-service
spring.cloud.gateway.routes[2].id=song-service
spring.cloud.gateway.routes[2].uri=lb://song-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/songs/**

# Route admin songs through song-service
spring.cloud.gateway.routes[3].id=song-service-admin
spring.cloud.gateway.routes[3].uri=lb://song-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/admin/songs/**

# Route to playlist-service
spring.cloud.gateway.routes[4].id=playlist-service
spring.cloud.gateway.routes[4].uri=lb://playlist-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/playlists/**

# Route to notification-service
spring.cloud.gateway.routes[5].id=notification-service
spring.cloud.gateway.routes[5].uri=lb://notification-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/admin/notifications/**

# Route admin users through user-service
spring.cloud.gateway.routes[6].id=user-service-admin
spring.cloud.gateway.routes[6].uri=lb://user-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/admin/users/**

# Route to admin-service
spring.cloud.gateway.routes[7].id=admin-service
spring.cloud.gateway.routes[7].uri=lb://admin-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/admin/**